# Generated by Django 2.2 on 2024-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
