# Generated by Django 2.2 on 2024-03-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Cafe', '0002_bill_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
    ]
