# Generated by Django 2.2 on 2024-03-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Cafe', '0003_refinedbill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
